### ISSUE TITLE
how do you actually use it?

### ISSUE THREAD

**Issue by verybigelephants** [aivarsi/framework-scraper-webuilder#2]
i don't understand. 

going by tutorial, i go to a specified framework URL, then the tutorial tells me to "Evaluate the specified JavaScript file (scraper)". how do i do that? am i supposed to edit the html headers in web inspector to include the javascript files hosted somewhere or what?

for example, if i were to scrape laravel documentation. what do i do? first, go here https://laravel.com/api/5.1/ and then what? how do i "evaluate the specified javascript file" 

and what specified javascript file? i found no help in readme.md neither

**Comment by aivarsi** [comment]
The whole thing is a WeBuilder plugin so to use it you need to install the plugin first. You can install it in 2 ways - either by zipping the files and installing the zip file via WeBuilder's menu Plugins -> Manage Plugins -> Install, or, if you plan to improve upon the plugin, install the plugin by creating %AppData%\Blumentals\WeBuilder\plugins\framework-scraper-webuilder and placing all files there.

After you have installed the plugin, you can access its functionality from Plugins menu.

The readme file describes how the plugin works, not how to use it. It is assumed that you are already familiar with WeBuilder plugins: http://help.blumentals.net/webuilder/plugins/index.htm

**Comment by verybigelephants** [comment]
oh thanks for the explanation! so i have installed the plugin into my rapidPHP, then click plugins->scrape frameworks->laravel and then browsed for the documentation. was the scraper go through the links and scrape information automatically? because i don't seem to get any laravel codehints in my laravel project after this

**Comment by aivarsi** [comment]
If all you wanted is Laravel code hints then you don't need this plugin. Just use menu Options -> Frameworks and check Laravel. The problem is that when you ran the plugin it deleted the original hint info before rescanning it. The plugin should have gone through all Laravel classes in documentation. If it didn't then you don't have full documentation anymore. You can restore the original data by finding libraries.sqlite under %apdpata%\Roaming\Blumentals and rewriting it with <Rapid PHP installation directory>\data\libraries\libraries.sqlite

This plugin is not for regular WeBuilder/Rapid PHP users but only for those who want to modify the existing auto-complete info or add additional frameworks.

If you're having further problems with hints, please contact the Rapid PHP support.

**Comment by verybigelephants** [comment]
the original laravel support doesn't work though :(

**Comment by kaitnieks** [comment]
Please contact customer support with specific screenshots, samples so that we can try to figure out what's wrong and help you. Did you restore the original libraries.sqlite?

**Comment by verybigelephants** [comment]
i already sent a message but understand that it's chirstmas and people need to enjoy holidays :) i will try to reinstall whole rapidphp and don't spam this place
